//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experiencia1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int codigo_cli { get; set; }
        public string nombre_cli { get; set; }
        public string direc_cli { get; set; }
        public string tel_cli { get; set; }
        public string correo_cli { get; set; }
        public int edad_cli { get; set; }
    }
}
