//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E.Propuesto_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int id_venta { get; set; }
        public int cantidad { get; set; }
        public Nullable<int> producto { get; set; }
    }
}
