//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMVC01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public string CódigoCliente { get; set; }
        public string Nombre { get; set; }
        public string Dirección { get; set; }
        public string Teléfono { get; set; }
        public string Correo_Electrónico { get; set; }
        public int Edad { get; set; }
    }
}
